# Generated by Django 3.0.4 on 2020-03-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
    ]
