# Generated by Django 3.0.4 on 2020-03-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codes', '0004_remove_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
    ]
